//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATOR> ATOR { get; set; }
        public virtual DbSet<AVALIACAO> AVALIACAO { get; set; }
        public virtual DbSet<CINEMA> CINEMA { get; set; }
        public virtual DbSet<CONTATO> CONTATO { get; set; }
        public virtual DbSet<DIRETOR> DIRETOR { get; set; }
        public virtual DbSet<FAVORITO> FAVORITO { get; set; }
        public virtual DbSet<FILME> FILME { get; set; }
        public virtual DbSet<POLTRONA> POLTRONA { get; set; }
        public virtual DbSet<SALA> SALA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<FILME_IMAGEM> FILME_IMAGEM { get; set; }
        public virtual DbSet<SESSAO> SESSAO { get; set; }
        public virtual DbSet<INGRESSO> INGRESSO { get; set; }
    }
}
