//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITO
    {
        public int FavoridoId { get; set; }
        public int FilmeId { get; set; }
        public int ClienteId { get; set; }
    
        public virtual FILME FILME { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
