//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILME()
        {
            this.AVALIACAO = new HashSet<AVALIACAO>();
            this.DIRETOR1 = new HashSet<DIRETOR>();
            this.FAVORITO = new HashSet<FAVORITO>();
            this.ATOR = new HashSet<ATOR>();
            this.FILME_IMAGEM = new HashSet<FILME_IMAGEM>();
            this.SESSAO = new HashSet<SESSAO>();
        }
    
        public int FilmeId { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Duracao { get; set; }
        public Nullable<int> Classificacao { get; set; }
        public string Diretor { get; set; }
        public string Distribuidora { get; set; }
        public Nullable<bool> Cartaz { get; set; }
        public Nullable<bool> Estreia { get; set; }
        public string Genero { get; set; }
        public string Trailer { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACAO> AVALIACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRETOR> DIRETOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITO> FAVORITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATOR> ATOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILME_IMAGEM> FILME_IMAGEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSAO> SESSAO { get; set; }
    }
}
