//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESSO
    {
        public int IngressoId { get; set; }
        public int PoltronaId { get; set; }
        public int ClienteId { get; set; }
        public int CinemaId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Pagamento { get; set; }
    
        public virtual CINEMA CINEMA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual POLTRONA POLTRONA { get; set; }
    }
}
